### ISSUE TITLE
Thumbnail is full width, but video is not?

### ISSUE THREAD

**Issue by BE-CH** [the-muda-organization/vimeo-lazyload#1]
Hello

I have an issue where the lazyloaded video will not be the same width as the thumbnail. This makes the video have a left and right border showing some of the thumbnail underneath. 

Example: https://i.imgur.com/74ctuVZ.png
This also happens on the demo: https://i.imgur.com/7cD0Uuk.png

I am pretty sure that the iFrame thinks its 100% of the thumbnail, but the actual video that is playing is not.

I tried fiddeling around with some calculations of padding-bottom but didn't seem to work.

**How would I get the actual video player to be the same size as the thumbnail?**

**Comment by jakubmuda** [comment]
It looks like Vimeo unlike Youtube add transparent padding when iFrame has different ratio than video. [https://jsfiddle.net/ps78nm50/](https://jsfiddle.net/ps78nm50/) .

It looks like I should add DIV with black background beneath iFrame to cover the thumbnail. I will take a look at this issue. 

Note: For optimal functionality thumbnail and video must have the same ratio

**Comment by jakubmuda** [comment]
Solved in v1.0.3

I added `background-color:#000` to iFrame and the thumbnail is never visible because the iFrame covers the entire container.
